### ISSUE TITLE
Saving game doesn't work

### ISSUE THREAD

**Issue by freestylofil** [barthap/inpg-checkers#14]
The game crashes with this traceback while saving a game:
`Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    main()
  File "src/main.py", line 6, in main
    app.main()
  File "C:\Users\freyf\Desktop\Filip\nauka\4. studia\S2\INPG\warcaby\inpg-checkers\src\app.py", line 31, in main
    self.__main_loop()
  File "C:\Users\freyf\Desktop\Filip\nauka\4. studia\S2\INPG\warcaby\inpg-checkers\src\app.py", line 60, in __main_loop
    self.scene_manager.current.update(events)
  File "C:\Users\freyf\Desktop\Filip\nauka\4. studia\S2\INPG\warcaby\inpg-checkers\src\game.py", line 256, in update
    self.save_game()
  File "C:\Users\freyf\Desktop\Filip\nauka\4. studia\S2\INPG\warcaby\inpg-checkers\src\game.py", line 67, in save_game
    with open(filename, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'saves\\save_Eustachy_Henryk_1527250433.dat'`

**Comment by barthap** [comment]
Fixed
